Modules/Website/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::prefix('website')->group(function() {
    Route::get('/', 'WebsiteController@index');
});
*/

Route::prefix('/')->group(function() {
    Route::get('/', 'HomeController');
    Route::get('/home', 'HomeController');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => [
        'auth',
    ]
],function() {
    Route::group([
        'prefix' => 'slideshows',
        'as' => 'slideshow.',
        'namespace' => 'Slideshows'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });

    Route::group([
        'prefix' => 'master',
        'as' => 'master.',
        'namespace' => 'Master'
    ], function() {
        Route::group([
            'prefix' => 'products',
            'as' => 'product.',
            'namespace' => 'Products'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'product-type',
            'as' => 'product_type.',
            'namespace' => 'ProductType'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'collections',
            'as' => 'collection.',
            'namespace' => 'Collections'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
    });

    Route::group([
        'prefix' => 'blogs',
        'as' => 'blog.',
        'namespace' => 'Blogs'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });
});

Modules/Website/Http/Controllers/Admin/Master/Collections/CreateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Collections;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class CreateController extends Controller
{
    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function __invoke()
    {
        return view('website::admin.master.collections.create');
    }
}

Modules/Website/Http/Controllers/Admin/Master/Collections/DeleteController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Collections;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\CollectionRepository;

class DeleteController extends Controller
{
    public $collection;
    public $title = 'Product Collection';

    public function __construct(CollectionRepository $collection)
    {
        $this->collection = $collection;
    }

    /**
     * Remove the specified resource from storage.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        try {
            $this->collection->delete($uuid);
            notice('success', "{$this->title} berhasil dihapus");
        } catch (\App\Exceptions\DeleteException $e) {
            notice('error', $e->getMessage());
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.master.collection.index');
    }
}

Modules/Website/Http/Controllers/Admin/Master/Collections/EditController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Collections;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;

class EditController extends Controller
{
    public $productType;
    public $title = 'Product Type';

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }

    /**
     * Show the form for editing the specified resource.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        $productType = $this->productType->find($uuid);
        return view('website::admin.product-types.edit', compact('productType'));
    }
}

Modules/Website/Http/Controllers/Admin/Master/Collections/IndexController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Collections;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\CollectionRepository;

class IndexController extends Controller
{
    public $collection;

    public function __construct(CollectionRepository $collection)
    {
        $this->collection = $collection;
    }
    /**
     * Display a home|beranda website
     * @return Renderable
     */
    public function __invoke(Request $request)
    {
        $filters = [];
        if($request->has('search')) {
            $filters['search'] = $request->search;
        }

        $collections = $this->collection->paginate($filters = $filters, $limit = 10);
        return view('website::admin.master.collections.index', compact('collections'));
    }
}

Modules/Website/Http/Controllers/Admin/Master/Collections/StoreController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Collections;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\CollectionRepository;
use Modules\Website\Http\Requests\Master\Collections\StoreRequest;

class StoreController extends Controller
{
    public $collection;
    public $title = 'Product Type';

    public function __construct(CollectionRepository $collection)
    {
        $this->collection = $collection;
    }

    /**
     * Store a newly created resource in storage.
     * @param StoreRequest $request
     * @return Renderable
     */
    public function __invoke(StoreRequest $request)
    {
        $data = $request->data();
        try {
            $this->collection->store($data);
            notice('success', "{$this->title} berhasil ditambahkan");
        } catch (\Exception $e) {
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.master.collection.index');
    }
}

Modules/Website/Http/Controllers/Admin/Master/Collections/UpdateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Collections;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;
use Modules\Website\Http\Requests\Master\ProductTypes\StoreRequest;

class UpdateController extends Controller
{
    public $productType;
    public $title = 'Product Type';

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }

    /**
     * Update the specified resource in storage.
     * @param StoreRequest $request
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(StoreRequest $request, string $uuid)
    {
        try {
            $this->productType->update($uuid, $request->data());
            notice('success', "{$this->title} berhasil diubah");
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.master.product_type.index');
    }
}

Modules/Website/Http/Controllers/Admin/Master/ProductType/CreateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\ProductType;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class CreateController extends Controller
{
    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function __invoke()
    {
        return view('website::admin.product-types.create');
    }
}

Modules/Website/Http/Controllers/Admin/Master/ProductType/DeleteController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\ProductType;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;

class DeleteController extends Controller
{
    public $productType;
    public $title = 'Product Type';

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }

    /**
     * Remove the specified resource from storage.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        try {
            $this->productType->delete($uuid);
            notice('success', "{$this->title} berhasil dihapus");
        } catch (\App\Exceptions\DeleteException $e) {
            notice('error', $e->getMessage());
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.master.product_type.index');
    }
}

Modules/Website/Http/Controllers/Admin/Master/ProductType/EditController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\ProductType;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;

class EditController extends Controller
{
    public $productType;
    public $title = 'Product Type';

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }

    /**
     * Show the form for editing the specified resource.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        $productType = $this->productType->find($uuid);
        return view('website::admin.product-types.edit', compact('productType'));
    }
}

Modules/Website/Http/Controllers/Admin/Master/ProductType/IndexController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\ProductType;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;

class IndexController extends Controller
{
    public $productType;

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }
    /**
     * Display a home|beranda website
     * @return Renderable
     */
    public function __invoke(Request $request)
    {
        $filters = [];
        if($request->has('search')) {
            $filters['search'] = $request->search;
        }

        $productTypes = $this->productType->paginate($filters = $filters, $limit = 10);
        return view('website::admin.product-types.index', compact('productTypes'));
    }
}

Modules/Website/Http/Controllers/Admin/Master/ProductType/StoreController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\ProductType;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;
use Modules\Website\Http\Requests\Master\ProductTypes\StoreRequest;

class StoreController extends Controller
{
    public $productType;
    public $title = 'Product Type';

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }

    /**
     * Store a newly created resource in storage.
     * @param StoreRequest $request
     * @return Renderable
     */
    public function __invoke(StoreRequest $request)
    {
        $data = $request->data();
        try {
            $this->productType->store($data);
            notice('success', "{$this->title} berhasil ditambahkan");
        } catch (\Exception $e) {
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.master.product_type.index');
    }
}

Modules/Website/Http/Controllers/Admin/Master/ProductType/UpdateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\ProductType;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;
use Modules\Website\Http\Requests\Master\ProductTypes\StoreRequest;

class UpdateController extends Controller
{
    public $productType;
    public $title = 'Product Type';

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }

    /**
     * Update the specified resource in storage.
     * @param StoreRequest $request
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(StoreRequest $request, string $uuid)
    {
        try {
            $this->productType->update($uuid, $request->data());
            notice('success', "{$this->title} berhasil diubah");
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.master.product_type.index');
    }
}

Modules/Website/Http/Controllers/Admin/Master/Products/CreateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Products;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductTypeRepository;

class CreateController extends Controller
{
    public $productType;
    public $title = 'Product';

    public function __construct(ProductTypeRepository $productType)
    {
        $this->productType = $productType;
    }
    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function __invoke()
    {
        $productTypes = $this->productType->fetch();

        return view(
            'website::admin.master.products.create',
            compact('productTypes')
        );
    }
}

Modules/Website/Http/Controllers/Admin/Master/Products/DeleteController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Master\Products;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\ProductRepository;

class DeleteController extends Controller
{
    public $product;
    public $title = 'Product';

    public function __construct(ProductRepository $product)
    {
        $this->product = $product;
    }

    /**
     * Remove the specified resource from storage.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        try {
            $this->product->delete($uuid);
            notice('success', "{$this->title} berhasil dihapus");
        } catch (\App\Exceptions\DeleteException $e) {
            notice('error', $e->getMessage());
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.master.product.index');
    }
}

Modules/Website/Resources/views/admin/master/products/create.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Add New Product') }}</div>

                <div class="card-body">
                    {{-- form input product --}}
                    <form method="post" action="{{ route('admin.master.product.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="inputTitle" class="form-label">Name</label>
                            <input name="name" value="{{ old('name') }}" placeholder="Input name" type="text" class="form-control" id="inputTitle" aria-describedby="emailHelp">
                            @error('name')
                                <div class="text-danger">{{ $errors->first('name') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputProductType" class="form-label">Product Type</label>
                            <select name="product_type_id" class="form-control" id="inputProductType">
                                <option value="" selected disabled>Pilih Product Type</option>
                                @foreach($productTypes as $type)
                                <option value="{{ $type->id }}" {{ old('product_type_id') == $type->id ? 'selected' : '' }}>{{ $type->title }}</option>
                                @endforeach
                            </select>
                            @error('product_type_id')
                                <div class="text-danger">{{ $errors->first('product_type_id') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputDescription" class="form-label">Description</label>
                            <textarea name="description" class="form-control" id="inputDescription" rows="3" placeholder="Input description">{{ old('description') }}</textarea>
                            @error('description')
                                <div class="text-danger">{{ $errors->first('description') }}</div>
                            @enderror
                        </div>

                        <div class="row g-3 justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-outline-secondary" href="{{ route('admin.master.product.index') }}" role="button">Cancel</a>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-primary">Save</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
@endpush

@push('scripts')
<script>
    ClassicEditor.create(document.querySelector('#inputDescription')).catch(error => {
        console.error(error);
    });
</script>
@endpush

Modules/Website/Resources/views/admin/master/products/edit.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Product') }}</div>

                <div class="card-body">
                    {{-- form input blog --}}
                    <form method="post" action="{{ route('admin.master.product.update', $product->uuid) }}" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="inputTitle" class="form-label">Name</label>
                            <input name="name" value="{{ old('name', $product->name) }}" placeholder="Input name" type="text" class="form-control" id="inputTitle" aria-describedby="emailHelp">
                            @error('title')
                                <div class="text-danger">{{ $errors->first('title') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputProductType" class="form-label">Product Type</label>
                            <select name="product_type_id" class="form-control" id="inputProductType">
                                <option value="" selected disabled>Pilih Product Type</option>
                                @foreach($productTypes as $type)
                                <option value="{{ $type->id }}" {{ old('product_type_id', $product->product_type_id) == $type->id ? 'selected' : '' }}>{{ $type->title }}</option>
                                @endforeach
                            </select>
                            @error('product_type_id')
                                <div class="text-danger">{{ $errors->first('product_type_id') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputDescription" class="form-label">Description</label>
                            <textarea name="description" class="form-control" id="inputDescription" rows="3" placeholder="Input description">{{ old('description', $product->description) }}</textarea>
                            @error('description')
                                <div class="text-danger">{{ $errors->first('description') }}</div>
                            @enderror
                        </div>

                        <div class="row g-3 justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-outline-secondary" href="{{ route('admin.master.product.index') }}" role="button">Cancel</a>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-primary">Save</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
@endpush

@push('scripts')
<script>
    ClassicEditor.create(document.querySelector('#inputDescription')).catch(error => {
        console.error(error);
    });
</script>
@endpush

Modules/Website/Resources/views/admin/master/products/index.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Product') }}</div>

                <div class="card-body">
                    {{-- add new product--}}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a class="btn btn-outline-primary" href="{{ route('admin.master.product.create') }}" role="button">Add New Product</a>
                    </div>

                    {{-- list product --}}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Product Type</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($products as $product)
                            @php $imageUrl = $product->image ? asset('storage/products/'.$product->image) : 'https://fakeimg.pl/300x100'; @endphp
                            <tr>
                                <td>{{ $product->name }}</td>
                                <td>{{ optional($product->type)->title ?? '-' }}</td>
                                <td>
                                    <div class="row g-3">
                                        <div class="col-auto">
                                            <a class="btn btn-outline-info" href="{{ route('admin.master.product.edit', $product->uuid) }}" role="button">Images</a>
                                        </div>
                                        <div class="col-auto">
                                            <a class="btn btn-outline-info" href="{{ route('admin.master.product.edit', $product->uuid) }}" role="button">Edit</a>
                                        </div>
                                        <div class="col-auto">
                                            <a class="btn btn-outline-danger" href="{{ route('admin.master.product.delete', $product->uuid) }}" role="button">Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @empty

                            @endforelse
                        </tbody>
                    </table>
                    {{ $products->appends(request()->query())->links() }}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection