Modules/Website/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::prefix('website')->group(function() {
    Route::get('/', 'WebsiteController@index');
});
*/

Route::prefix('/')->group(function() {
    Route::get('/', 'HomeController');
    Route::get('/home', 'HomeController');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => [
        'auth',
    ]
],function() {
    Route::group([
        'prefix' => 'slideshows',
        'as' => 'slideshow.',
        'namespace' => 'Slideshows'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });

    Route::group([
        'prefix' => 'master',
        'as' => 'master.',
        'namespace' => 'Master'
    ], function() {
        Route::group([
            'prefix' => 'products',
            'as' => 'product.',
            'namespace' => 'Products'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'product-type',
            'as' => 'product_type.',
            'namespace' => 'ProductType'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'collections',
            'as' => 'collection.',
            'namespace' => 'Collections'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
    });

    Route::group([
        'prefix' => 'blogs',
        'as' => 'blog.',
        'namespace' => 'Blogs'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });
});

Modules/Website/Http/Controllers/Admin/Slideshows/CreateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Slideshows;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class CreateController extends Controller
{
    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function __invoke()
    {
        return view('website::admin.slideshows.create');
    }
}

Modules/Website/Http/Controllers/Admin/Slideshows/DeleteController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Slideshows;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\SlideshowRepository;

class DeleteController extends Controller
{
    public $slideshow;
    public $title = 'Slideshow';

    public function __construct(SlideshowRepository $slideshow)
    {
        $this->slideshow = $slideshow;
    }

    /**
     * Remove the specified resource from storage.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        try {
            $this->slideshow->delete($uuid);
            notice('success', "{$this->title} berhasil dihapus");
        } catch (\App\Exceptions\DeleteException $e) {
            notice('error', $e->getMessage());
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.slideshow.index');
    }
}

Modules/Website/Http/Controllers/Admin/Slideshows/EditController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Slideshows;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\SlideshowRepository;

class EditController extends Controller
{
    public $slideshow;
    public $title = 'Slideshow';

    public function __construct(SlideshowRepository $slideshow)
    {
        $this->slideshow = $slideshow;
    }

    /**
     * Show the form for editing the specified resource.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        $slideshow = $this->slideshow->find($uuid);
        return view('website::admin.slideshows.edit', compact('slideshow'));
    }
}

Modules/Website/Http/Controllers/Admin/Slideshows/IndexController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Slideshows;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\SlideshowRepository;

class IndexController extends Controller
{
    public $slideshow;

    public function __construct(SlideshowRepository $slideshow)
    {
        $this->slideshow = $slideshow;
    }

    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function __invoke()
    {
        $filters = [];

        $slideshows = $this->slideshow->paginate($filters = $filters, $limit = 10);
        return view('website::admin.slideshows.index', compact('slideshows'));
    }
}

Modules/Website/Http/Controllers/Admin/Slideshows/StoreController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Slideshows;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\SlideshowRepository;
use Modules\Website\Http\Requests\Slideshows\StoreRequest;

class StoreController extends Controller
{
    public $slideshow;
    public $title = 'Slideshow';

    public function __construct(SlideshowRepository $slideshow)
    {
        $this->slideshow = $slideshow;
    }

    /**
     * Store a newly created resource in storage.
     * @param StoreRequest $request
     * @return Renderable
     */
    public function __invoke(StoreRequest $request)
    {
        $data = $request->data();
        try {
            $this->slideshow->store($data);
            notice('success', "{$this->title} berhasil ditambahkan");
        } catch (\Exception $e) {
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.slideshow.index');
    }
}

Modules/Website/Http/Controllers/Admin/Slideshows/UpdateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Slideshows;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\SlideshowRepository;
use Modules\Website\Http\Requests\Slideshows\StoreRequest;

class UpdateController extends Controller
{
    public $slideshow;
    public $title = 'Slideshow';

    public function __construct(SlideshowRepository $slideshow)
    {
        $this->slideshow = $slideshow;
    }

    /**
     * Update the specified resource in storage.
     * @param StoreRequest $request
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(StoreRequest $request, string $uuid)
    {
        try {
            $this->slideshow->update($uuid, $request->data());
            notice('success', "{$this->title} berhasil diubah");
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.slideshow.index');
    }
}

Modules/Website/Resources/views/admin/slideshows/create.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Add New Slideshow') }}</div>

                <div class="card-body">
                    {{-- form input slideshow --}}
                    <form method="post" action="{{ route('admin.slideshow.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="inputTitle" class="form-label">Title</label>
                            <input name="title" value="{{ old('title') }}" placeholder="Input title" type="text" class="form-control" id="inputTitle" aria-describedby="emailHelp">
                            @error('title')
                                <div class="text-danger">{{ $errors->first('title') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputDescription" class="form-label">Description</label>
                            <textarea name="description" class="form-control" id="inputDescription" rows="3" placeholder="Input description">{{ old('description') }}</textarea>
                            @error('description')
                                <div class="text-danger">{{ $errors->first('description') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputEmbedUrl" class="form-label">Embed Url</label>
                            <input name="embed_url" value="{{ old('embed_url') }}" placeholder="Input embed url ex: https://sinurapps.com" type="text" class="form-control" id="inputEmbedUrl" aria-describedby="emailHelp">
                            @error('embed_url')
                                <div class="text-danger">{{ $errors->first('embed_url') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputImage" class="form-label">Upload Image</label>
                            <input name="image" type="file" id="inputImage" class="form-control" aria-label="file example" accept=".jpeg,.jpg,.png">
                            @error('image')
                                <div class="text-danger">{{ $errors->first('image') }}</div>
                            @enderror
                        </div>

                        <div class="row g-3 justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-outline-secondary" href="{{ route('admin.slideshow.index') }}" role="button">Cancel</a>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-primary">Save</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
@endpush

@push('scripts')
<script>
    ClassicEditor.create(document.querySelector('#inputDescription')).catch(error => {
        console.error(error);
    });
</script>
@endpush

Modules/Website/Resources/views/admin/slideshows/edit.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Slideshow') }}</div>

                <div class="card-body">
                    {{-- form input slideshow --}}
                    <form method="post" action="{{ route('admin.slideshow.update', $slideshow->uuid) }}" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="inputTitle" class="form-label">Title</label>
                            <input name="title" value="{{ old('title', $slideshow->title) }}" placeholder="Input title" type="text" class="form-control" id="inputTitle" aria-describedby="emailHelp">
                            @error('title')
                                <div class="text-danger">{{ $errors->first('title') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputDescription" class="form-label">Description</label>
                            <textarea name="description" class="form-control" id="inputDescription" rows="3" placeholder="Input description">{{ old('description', $slideshow->description) }}</textarea>
                            @error('description')
                                <div class="text-danger">{{ $errors->first('description') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputEmbedUrl" class="form-label">Embed Url</label>
                            <input name="embed_url" value="{{ old('embed_url', $slideshow->embed_url) }}" placeholder="Input embed url ex: https://sinurapps.com" type="text" class="form-control" id="inputEmbedUrl" aria-describedby="emailHelp">
                            @error('embed_url')
                                <div class="text-danger">{{ $errors->first('embed_url') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <img src="{{ asset('storage/slideshows/'.$slideshow->image) }}" class="d-block img-thumbnail mb-3">
                            <label for="inputImage" class="form-label">Change Image</label>
                            <input name="image" type="file" id="inputImage" class="form-control" aria-label="file example" accept=".jpeg,.jpg,.png">
                            @error('image')
                                <div class="text-danger">{{ $errors->first('image') }}</div>
                            @enderror
                        </div>

                        <div class="row g-3 justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-outline-secondary" href="{{ route('admin.slideshow.index') }}" role="button">Cancel</a>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-primary">Save</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
@endpush

@push('scripts')
<script>
    ClassicEditor.create(document.querySelector('#inputDescription')).catch(error => {
        console.error(error);
    });
</script>
@endpush

Modules/Website/Resources/views/admin/slideshows/index.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Slideshow') }}</div>

                <div class="card-body">
                    {{-- add new slideshow--}}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a class="btn btn-outline-primary" href="{{ route('admin.slideshow.create') }}" role="button">Add New Slideshow</a>
                    </div>

                    {{-- list slideshow --}}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Thumbnail</th>
                                <th>Title</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($slideshows as $slideshow)
                            @php $imageUrl = $slideshow->image ? asset('storage/slideshows/'.$slideshow->image) : 'https://fakeimg.pl/300x100'; @endphp
                            <tr>
                                <td><img src="{{ $imageUrl }}" class="img-thumbnail" alt="thumbnail" width="300px"></td>
                                <td>{{ $slideshow->title }}</td>
                                <td>
                                    <div class="row g-3">
                                        <div class="col-auto">
                                            <a class="btn btn-outline-info" href="{{ route('admin.slideshow.edit', $slideshow->uuid) }}" role="button">Edit</a>
                                        </div>
                                        <div class="col-auto">
                                            <a class="btn btn-outline-danger" href="{{ route('admin.slideshow.delete', $slideshow->uuid) }}" role="button">Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @empty

                            @endforelse
                        </tbody>
                    </table>
                    {{ $slideshows->appends(request()->query())->links() }}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection