Modules/Website/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::prefix('website')->group(function() {
    Route::get('/', 'WebsiteController@index');
});
*/

Route::prefix('/')->group(function() {
    Route::get('/', 'HomeController');
    Route::get('/home', 'HomeController');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => [
        'auth',
    ]
],function() {
    Route::group([
        'prefix' => 'slideshows',
        'as' => 'slideshow.',
        'namespace' => 'Slideshows'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });

    Route::group([
        'prefix' => 'master',
        'as' => 'master.',
        'namespace' => 'Master'
    ], function() {
        Route::group([
            'prefix' => 'products',
            'as' => 'product.',
            'namespace' => 'Products'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'product-type',
            'as' => 'product_type.',
            'namespace' => 'ProductType'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'collections',
            'as' => 'collection.',
            'namespace' => 'Collections'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
    });

    Route::group([
        'prefix' => 'blogs',
        'as' => 'blog.',
        'namespace' => 'Blogs'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });
});

Modules/Website/Http/Controllers/Admin/Blogs/CreateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Blogs;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class CreateController extends Controller
{
    /**
     * Display a home|beranda website
     * @return Renderable
     */
    public function __invoke()
    {
        return view('website::admin.blogs.create');
    }
}

Modules/Website/Http/Controllers/Admin/Blogs/DeleteController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Blogs;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\BlogRepository;

class DeleteController extends Controller
{
    public $blog;
    public $title = 'Blog';

    public function __construct(BlogRepository $blog)
    {
        $this->blog = $blog;
    }
    /**
     * Remove the specified resource from storage.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        try {
            $this->blog->delete($uuid);
            notice('success', "{$this->title} berhasil dihapus");
        } catch (\App\Exceptions\DeleteException $e) {
            notice('error', $e->getMessage());
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.blog.index');
    }
}

Modules/Website/Http/Controllers/Admin/Blogs/EditController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Blogs;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\BlogRepository;

class EditController extends Controller
{
    public $blog;
    public $title = 'Blog';

    public function __construct(BlogRepository $blog)
    {
        $this->blog = $blog;
    }
    /**
     * Show the form for editing the specified resource.
     * @param string $uuid
     * @return Renderable
     */
    public function __invoke(string $uuid)
    {
        $blog = $this->blog->find($uuid);
        return view('website::admin.blogs.edit', compact('blog'));
    }
}

Modules/Website/Http/Controllers/Admin/Blogs/IndexController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Blogs;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\BlogRepository;

class IndexController extends Controller
{
    public $blog;

    public function __construct(BlogRepository $blog)
    {
        $this->blog = $blog;
    }
    /**
     * Display a home|beranda website
     * @return Renderable
     */
    public function __invoke(Request $request)
    {
        $filters = [];
        if($request->has('search')) {
            $filters['search'] = $request->search;
        }

        $blogs = $this->blog->paginate($filters = $filters, $limit = 10);
        return view('website::admin.blogs.index', compact('blogs'));
    }
}

Modules/Website/Http/Controllers/Admin/Blogs/StoreController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Blogs;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\BlogRepository;
use Modules\Website\Http\Requests\Blogs\StoreRequest;

class StoreController extends Controller
{
    public $blog;
    public $title = 'Blog';

    public function __construct(BlogRepository $blog)
    {
        $this->blog = $blog;
    }
    /**
     * Display a home|beranda website
     * @return Renderable
     */
    public function __invoke(StoreRequest $request)
    {
        $data = $request->data();
        try {
            $this->blog->store($data);
            notice('success', "{$this->title} berhasil ditambahkan");
        } catch (\Exception $e) {
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.blog.index');
    }
}

Modules/Website/Http/Controllers/Admin/Blogs/UpdateController.php
<?php

namespace Modules\Website\Http\Controllers\Admin\Blogs;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Website\Repositories\BlogRepository;
use Modules\Website\Http\Requests\Blogs\StoreRequest;

class UpdateController extends Controller
{
    public $blog;
    public $title = 'Blog';

    public function __construct(BlogRepository $blog)
    {
        $this->blog = $blog;
    }
    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function __invoke(StoreRequest $request, string $uuid)
    {
        try {
            $this->blog->update($uuid, $request->data());
            notice('success', "{$this->title} berhasil diubah");
        } catch (\Exception $e) {
#            panic($e);
            notice('error', "Terjadi kesalahan, silakan hubungi admin");
        }

        return redirect()->route('admin.blog.index');
    }
}

Modules/Website/Resources/views/admin/blogs/create.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Add New Blog') }}</div>

                <div class="card-body">
                    {{-- form input blog --}}
                    <form method="post" action="{{ route('admin.blog.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="inputTitle" class="form-label">Title</label>
                            <input name="title" value="{{ old('title') }}" placeholder="Input title" type="text" class="form-control" id="inputTitle" aria-describedby="emailHelp">
                            @error('title')
                                <div class="text-danger">{{ $errors->first('title') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputDescription" class="form-label">Description</label>
                            <textarea name="description" class="form-control" id="inputDescription" rows="3" placeholder="Input description">{{ old('description') }}</textarea>
                            @error('description')
                                <div class="text-danger">{{ $errors->first('description') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputEmbedUrl" class="form-label">Embed Video Url</label>
                            <input name="embed_url" value="{{ old('embed_url') }}" placeholder="Input embed video url ex: https://www.youtube.com/embed/9GfoQWHqXEA" type="text" class="form-control" id="inputEmbedUrl" aria-describedby="emailHelp">
                            @error('embed_url')
                                <div class="text-danger">{{ $errors->first('embed_url') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputImage" class="form-label">Upload Image</label>
                            <input name="image" type="file" id="inputImage" class="form-control" aria-label="file example" accept=".jpeg,.jpg,.png">
                            @error('image')
                                <div class="text-danger">{{ $errors->first('image') }}</div>
                            @enderror
                        </div>

                        <div class="row g-3 justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-outline-secondary" href="{{ route('admin.blog.index') }}" role="button">Cancel</a>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-primary">Save</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Modules/Website/Resources/views/admin/blogs/edit.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Blog') }}</div>

                <div class="card-body">
                    {{-- form input blog --}}
                    <form method="post" action="{{ route('admin.blog.update', $blog->uuid) }}" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="inputTitle" class="form-label">Title</label>
                            <input name="title" value="{{ old('title', $blog->title) }}" placeholder="Input title" type="text" class="form-control" id="inputTitle" aria-describedby="emailHelp">
                            @error('title')
                                <div class="text-danger">{{ $errors->first('title') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputDescription" class="form-label">Description</label>
                            <textarea name="description" class="form-control" id="inputDescription" rows="3" placeholder="Input description">{{ old('description', $blog->description) }}</textarea>
                            @error('description')
                                <div class="text-danger">{{ $errors->first('description') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="inputEmbedUrl" class="form-label">Embed Video Url</label>
                            <input name="embed_url" value="{{ old('embed_url', $blog->embed_url) }}" placeholder="Input embed video url ex: https://www.youtube.com/embed/9GfoQWHqXEA" type="text" class="form-control" id="inputEmbedUrl" aria-describedby="emailHelp">
                            @error('embed_url')
                                <div class="text-danger">{{ $errors->first('embed_url') }}</div>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <img src="{{ asset('storage/blogs/'.$blog->image) }}" class="d-block img-thumbnail mb-3">
                            <label for="inputImage" class="form-label">Change Image</label>
                            <input name="image" type="file" id="inputImage" class="form-control" aria-label="file example" accept=".jpeg,.jpg,.png">
                            @error('image')
                                <div class="text-danger">{{ $errors->first('image') }}</div>
                            @enderror
                        </div>

                        <div class="row g-3 justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-outline-secondary" href="{{ route('admin.blog.index') }}" role="button">Cancel</a>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-primary">Save</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Modules/Website/Resources/views/admin/blogs/index.blade.php
@extends('website::layouts.admin.app')

@php
@endphp
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('List Blog') }}</div>

                <div class="card-body">
                    {{-- add new blog--}}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a class="btn btn-outline-primary" href="{{ route('admin.blog.create') }}" role="button">Add New Blog</a>
                    </div>

                    {{-- filter list blogs --}}
                    <form action="">
                        <div class="row g-3 justify-content-end">
                            <div class="col-auto">
                                <input name="search" type="text" class="form-control" value="{{ request('search') }}" placeholder="Search input">
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-secondary">Search</button>
                            </div>
                        </div>
                    </form>

                    {{-- list blogs --}}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Thumbnail</th>
                                <th>Title</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($blogs as $blog)
                            @php $imageUrl = $blog->image ? asset('storage/blogs/'.$blog->image) : 'https://fakeimg.pl/20x30'; @endphp
                            <tr>
                                <td><img src="{{ $imageUrl }}" class="img-thumbnail" alt="thumbnail" width="50px"></td>
                                <td>{{ $blog->title }}</td>
                                <td>
                                    <div class="row g-3">
                                        <div class="col-auto">
                                            <a class="btn btn-outline-info" href="{{ route('admin.blog.edit', $blog->uuid) }}" role="button">Edit</a>
                                        </div>
                                        <div class="col-auto">
                                            <a class="btn btn-outline-danger" href="{{ route('admin.blog.delete', $blog->uuid) }}" role="button">Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @empty

                            @endforelse
                        </tbody>
                    </table>
                    {{ $blogs->appends(request()->query())->links() }}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection