Modules/Website/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::prefix('website')->group(function() {
    Route::get('/', 'WebsiteController@index');
});
*/

Route::prefix('/')->group(function() {
    Route::get('/', 'HomeController');
    Route::get('/home', 'HomeController');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => [
        'auth',
    ]
],function() {
    Route::group([
        'prefix' => 'slideshows',
        'as' => 'slideshow.',
        'namespace' => 'Slideshows'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });

    Route::group([
        'prefix' => 'master',
        'as' => 'master.',
        'namespace' => 'Master'
    ], function() {
        Route::group([
            'prefix' => 'products',
            'as' => 'product.',
            'namespace' => 'Products'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'product-type',
            'as' => 'product_type.',
            'namespace' => 'ProductType'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
        Route::group([
            'prefix' => 'collections',
            'as' => 'collection.',
            'namespace' => 'Collections'
        ], function() {
            Route::get('/', 'IndexController')->name('index');
            Route::get('/create', 'CreateController')->name('create');
            Route::post('/store', 'StoreController')->name('store');
            Route::get('{uuid}/edit', 'EditController')->name('edit');
            Route::post('{uuid}/update', 'UpdateController')->name('update');
            Route::get('{uuid}/delete', 'DeleteController')->name('delete');
        });
    });

    Route::group([
        'prefix' => 'blogs',
        'as' => 'blog.',
        'namespace' => 'Blogs'
    ], function() {
        Route::get('/', 'IndexController')->name('index');
        Route::get('/create', 'CreateController')->name('create');
        Route::post('/store', 'StoreController')->name('store');
        Route::get('{uuid}/edit', 'EditController')->name('edit');
        Route::post('{uuid}/update', 'UpdateController')->name('update');
        Route::get('{uuid}/delete', 'DeleteController')->name('delete');
    });
});

Modules/Website/Resources/views/layouts/admin/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- Bootstrap Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    @stack('styles')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        @guest
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.slideshow.index') }}">{{ __('Slideshow') }}</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Order
                                </a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.master.product_type.index') }}">Confirmation</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Master Data
                                </a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.master.product.index') }}">Product</a>
                                    <a class="dropdown-item" href="{{ route('admin.master.product_type.index') }}">Product Type</a>
                                    <a class="dropdown-item" href="{{ route('admin.master.collection.index') }}">Product Collection</a>
                                    <a class="dropdown-item" href="{{ route('admin.master.product_type.index') }}">Product Tagging</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.blog.index') }}">{{ __('Blog') }}</a>
                            </li>
                        @endguest
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>
    @if(session()->has("notice"))
        @php
            $value = Session::get('notice');
        @endphp
        @if (is_array($value))
            <script>
                @foreach ($value as $data)
                    @if ($data['labelClass'] == 'success')
                        toastr["success"]("{{ $data['content'] }}");
                    @endif
                    @if ($data['labelClass'] == 'error')
                        toastr["error"]("{{ $data['content'] }}");
                    @endif
                @endforeach
            </script>
        @endif
        @php
            Session::forget('notice');
        @endphp
    @endif
    @stack('scripts')
</body>
</html>